language: node_js
node_js:
  - "stable"
before_script:
  - npm install grunt-cli -g
  - npm install bower -g
  - bower install
  - gem update --system
  - gem install compass
script:
  - node generate-html.js
  - grunt prod --absolutePaths=true
  - grunt deploy-ftp --dest="httpdocs/"
